### ISSUE TITLE
data elements 

### ISSUE THREAD

**Issue by jungdee** [blazzbyte/OpenInterpreterUI#7]
Hi I'm using open-interpreter as bigquery client interpreter.
so most of outputs are dataframe, although open-interpreter's output is raw strings,
Any ideas on how to print output using data elements like  st.dataframe?
Additionally, I want to draw chart elements with that data.

**Comment by IA-Programming** [comment]
it seems possible to make what you are mentioning but the unique way that I see that possible is with a parser to seek a pattern into the answer and replace it with and element like in the video:
https://youtu.be/4sPnOqeUDmk?list=TLGG5KJRkm-s0qYwOTEyMjAyMw
that is within this documentation:
https://docs.streamlit.io/knowledge-base/tutorials/build-conversational-apps
