### ISSUE TITLE
local support

### ISSUE THREAD

**Issue by chrisbraddock** [blazzbyte/OpenInterpreterUI#9]
Does this support local models the [way open interpreter does](https://docs.openinterpreter.com/usage/terminal/arguments#local-or-l)?

**Comment by IA-Programming** [comment]
sadly this project does not include that feature still. feel  free to contribute if you want this feature, or if you can't be free to help us to add this and other more features contributing with a coffee.

<a href="https://www.buymeacoffee.com/blazzmocompany"><img src="https://img.buymeacoffee.com/button-api/?text=Buy me a coffee&emoji=&slug=blazzmocompany&button_colour=40DCA5&font_colour=ffffff&font_family=Cookie&outline_colour=000000&coffee_colour=FFDD00"></a>

**Comment by chrisbraddock** [comment]
I'm just evaluating tools at the moment and Python is definitely not my first language. If I use your tool in a successful project you bet, until then I'm a "starving dev" like anyone else. :) Thanks and good luck!

**Comment by blazzbyte** [comment]
@chrisbraddock in latest commit was added local support through llmstudio and Ollama, take into consideration that can be used in cloud if you open your server maybe using ngrok to use directly in our demo in cloud if you like

**Comment by kindzhon** [comment]
I try ollama,but it couldn't work,can't connect localhost:11434,but webui is working fine.
